on:
  push:
  workflow_dispatch:

          if (Test-Path "src/Sentinel.Hook/build/SentinelHook.dll") {
            copy src/Sentinel.Hook/build/SentinelHook.dll publish/cli/
            copy src/Sentinel.Hook/build/SentinelHook.dll publish/loader/
          } elseif (Test-Path "src/Sentinel.Hook/build/Release/SentinelHook.dll") {
            copy src/Sentinel.Hook/build/Release/SentinelHook.dll publish/cli/
            copy src/Sentinel.Hook/build/Release/SentinelHook.dll publish/loader/
          }
        shell: pwsh
